### ISSUE TITLE
Question: show a custom view

### ISSUE THREAD

**Issue by aresares** [rakshakhegde/Diffre#1]
Hi, can I show a custom view inside progressBar, not just a string but an ImageView with some text

**Comment by rakshakhegde** [comment]
Sure. But I'm not sure how it would look like with the kind of animation done here.

**Comment by aresares** [comment]
any idea how to do it, I only need the progress bar,not the animation. I searched on internet on how to convert view/layout in paint but no result. (I'm not good in android)
